#%RAML 1.0 Trait
headers:
  X-Cms-ClientId:
    required: true
    type: string
    example: "f490d357-4fcfcdsertc"    
  X-Cms-ClientSecret:
    required: true
    type: string
    example: "f490d357-ug74lkhgi" 