#%RAML 1.0 Trait
queryParameters:
  email:
    type: string
    required: false
    example: "abc@gmail.com"
  phoneCountry:
    type: string
    required: false    
    example: "+91"
  phoneNumber:
    type: string    
    required: false
    example: "9123456789"
  registrationDate:
    type: string
    required: false
    example: "23-26-2025"
      
       


      